image: "${GITLAB_DOCKER_PROXY}/eclipse-temurin:25-jdk-alpine"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GITLAB_DOCKER_PROXY: "gitlab.education.tbank.ru:443/backend-academy-java-2025/lecture-materials/dependency_proxy/containers"

.maven-cache: &maven-cache
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_PROTECTED == 'true'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - build
  - lint
  - test

cache:
  <<: *maven-cache
  policy: pull

build:
  stage: build
  timeout: 30m
  cache:
    <<: *maven-cache
    policy: pull-push
  script:
    - apk add --no-cache gcompat
    - ./mvnw --batch-mode --no-transfer-progress package -DskipTests=true -Djacoco.skip=true

lint:
  stage: lint
  timeout: 20m
  needs:
    - build
  script:
    - apk add --no-cache gcompat
    - ./mvnw --batch-mode --no-transfer-progress -pl bot,scrapper -am compile spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check

test:
  stage: test
  timeout: 40m
  needs:
    - build
  script:
    - apk add --no-cache gcompat
    - ./mvnw --batch-mode --no-transfer-progress -pl bot,scrapper -am test -DskipITs=true -Djacoco.skip=true
