services:
  scrapper:
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    container_name: link-tracker-scrapper
    environment:
      STACKOVERFLOW_KEY: ${STACKOVERFLOW_KEY}
      STACKOVERFLOW_ACCESS_KEY: ${STACKOVERFLOW_ACCESS_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      APP_BOT_BASE_URL: ${APP_BOT_BASE_URL:-http://bot:8080}
      APP_SCHEDULER_ENABLED: ${APP_SCHEDULER_ENABLED:-true}
      APP_SCHEDULER_INTERVAL: ${APP_SCHEDULER_INTERVAL:-30s}
      APP_GITHUB_BASE_URL: ${APP_GITHUB_BASE_URL:-https://api.github.com}
      APP_STACKOVERFLOW_BASE_URL: ${APP_STACKOVERFLOW_BASE_URL:-https://api.stackexchange.com}
    ports:
      - "8081:8081"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: link-tracker-bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      APP_TELEGRAM_POLLING_ENABLED: ${APP_TELEGRAM_POLLING_ENABLED}
      APP_TELEGRAM_URL: ${APP_TELEGRAM_URL}
      APP_SCRAPPER_BASE_URL: ${APP_SCRAPPER_BASE_URL:-http://scrapper:8081}
    ports:
      - "8080:8080"
    depends_on:
      - scrapper
