server:
  port: 8080

spring:
  application:
    name: bot
  config:
    import: optional:file:.env[.properties],optional:file:bot/.env[.properties]

app:
  telegram:
    url: ${APP_TELEGRAM_URL:https://api.telegram.org/bot}
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: ${APP_TELEGRAM_UPDATE_LISTENER_SLEEP:1s}
    polling-enabled: ${APP_TELEGRAM_POLLING_ENABLED:true}
    debug: ${APP_TELEGRAM_DEBUG:false}
